### ISSUE TITLE
TypeError: __init()__ got an unexpected keyword argument 'metric'

### ISSUE THREAD

**Issue by zhoumu1990** [neeharperi/nuscenes-lt3d#1]
nice job, when using the nuscenes devkit to evaluate, an error in nuscene_dataset.py lin 702 needs to modify. 
from "metric = metric_type" to "metric_type=metric_type".
FYI

**Comment by neeharperi** [comment]
Hi @zhoumu1990, 
Thanks for pointing this out. I've pushed a fix in the LT3D repository. 

Please let me know if you have any other questions. 
Neehar
